### ISSUE TITLE
Chrome and firefox percent encode apos in address bar query strings

### ISSUE THREAD

**Issue by dmaccormack** [jsonurl/jsonurl-js#96]
Chrome and firefox both percent encode apostrophe in URL query strings. This can be mitigated by using options.impliedStringLiterals, but that has the side effect that other literal types can't be represented.

A new grammar option that removes apostrophy, uses an escape-based syntax rather than the encoding-based syntax, and uses a different syntax to distinguish between true, false, null, number, and string would solve this problem.

**Comment by eyalw** [comment]
Yes, I've seen this happen too. 
I saw Mixpanel solving this by replacing query params enitrely with Hashes! Hashes apos do not convert to percent.
yes!
so their entire site works with hashes and no query params. and I copied their approach

**Comment by dkozar** [comment]
It could be great if the "apostrophe" issue could be resolved. Then we'd all use this library! :) 

FYI I found the same issue with other libraries which use the apostrophe character (like JSURL - the _apostrophe_ issue [here](https://github.com/Sage/jsurl/issues/15)). Couple of years ago browsers started encoding apostrophe in the URL to _%27_ because of some security concerns. And this brings the noise into the URL (the link still works).

I'm aware you're out of characters you could use, but possibly you can come up with something? :)

Thanks!

**Comment by dmaccormack** [comment]
> It could be great if the "apostrophe" issue could be resolved. Then we'd all use this library! :)
> 

Hi, @dkozar,

Thanks for the inquiry! :) This issue was solved with the Address Bar Query String Friendly (AQF) syntax, committed with #160 and available in v1.1.4 on [npmjs](https://www.npmjs.com/package/@jsonurl/jsonurl/v/1.1.4).

Per [jsonurl.org](https://www.jsonurl.org/#aqf) the basic idea is this:
> Special consideration should be taken when using JSON→URL in a browser address bar. Some browsers may change ' to %x27, which interferes with the string literal syntax described above. To sidestep this problem JSON→URL can optionally use escape sequences in string literals, rather than relying on quotes and encoding. An escape sequence begins with !, because \ is not allowed in a URL query string.

You can find complete details in [the spec](https://github.com/jsonurl/specification/#296-address-bar-query-string-friendly).
